version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,apigateway,cloudwatch,logs,iam,sqs,sns,stepfunctions,ssm,cloudformation
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
